devices:
  get:
    summary: 'Список устройств аккаунта'
    tags:
      - settings
    security:
      - BearerAuth: []
    responses:
      200:
        $ref: '../responses/settings/devices.yaml#/200'
      401:
        $ref: '../responses/entity.yaml#/401_JWT'
      429:
        $ref: '../responses/entity.yaml#/429_TO_MANY_REQUESTS'
      500:
        $ref: '../responses/entity.yaml#/500_INTERNAL_SERVER'
